# Configure this Discovery Server
eureka:
  client:  
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5 # DO NOT DO THIS IN PRODUCTION
     
server:
  port: 2222   # HTTP (Tomcat) port

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  application:
    name: persistence-service
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nimesh
    name: nimesh
    username: nimesh
    password: nimesh
    
  jpa:
    database: POSTGRESQL
    show_sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.use_minimal_puts: true
      hibernate.hbm2ddl.auto: update
  devtools:
    restart:
      enabled: true
  
liquibase:
  change-log: classpath:liquibase/master.xml
  contexts: dev
  
endpoints:
  info:
    id: information
    sensitive: false
    enabled: true
 
info:
  app:
    name: Persistence Service
    description: Persistence Service helps other services interact with the database.
    version: 1
    
persistence:
  security:
    xauth:
      token: IamAweS0Me
      validityPeriod: 8640000
  async:
    corePoolSize: 5
    maxPoolSize: 50
    queueCapacity: 10000 
    

